import type { GenerateParams } from "./prompts.js";

// A fixture deck for MOCK_LLM=1: every layout once, so the editor, the
// exporters and the tests can run without a key.
export function mockDeckJson(p: GenerateParams, sourceNames: string[]): { title: string; subtitle: string | null; slides: Record<string, unknown>[] } {
  const ms = p.lang === "ms";
  const title = p.title || (ms ? "Deck contoh" : "Sample deck");
  const src = sourceNames[0] ?? (ms ? "sumber" : "source");
  const s: Record<string, unknown>[] = [
    { layout: "title", title, subtitle: p.prompt.slice(0, 120) || (ms ? "Dijana tanpa kunci API" : "Generated without an API key"), notes: ms ? "Slaid tajuk." : "Title slide.", citations: [] },
    { layout: "section", title: ms ? "Apa yang berubah" : "What changed", subtitle: ms ? "Instrumen, tarikh, skop" : "Instrument, dates, scope", citations: [] },
    { layout: "bullets", kicker: "THE RULE", title: ms ? "Had 2% untuk asid salisilik dalam produk bilas" : "Salicylic acid is capped at 2% in rinse-off", body: null, bullets: [ms ? "Annex III entri 98 menetapkan had" : "Annex III entry 98 sets the limit", ms ? "Produk tinggal kekal pada 0.5%" : "Leave-on stays at 0.5%", ms ? "Label wajib: bukan untuk kanak-kanak bawah 3 tahun" : "Mandatory label: not for children under 3", `[SAHKAN: ${ms ? "tarikh kuat kuasa di Malaysia" : "Malaysian effective date"}]`], notes: ms ? "Nyatakan entri dan had. Kemudian sebut pengecualian syampu." : "State the entry and the limit, then the shampoo exception.", citations: ["EC 1223/2009 Annex III entry 98", `${src}`] },
    { layout: "chart", kicker: "THE EVIDENCE", title: ms ? "Aduan naik dua kali ganda dalam tiga tahun" : "Complaints doubled in three years", chart: { kind: "column", categories: ["2023", "2024", "2025"], series: [{ name: ms ? "Aduan" : "Complaints", values: [412, 610, 838] }], unit: ms ? "bilangan" : "count", source: `${src}` }, bullets: [ms ? "Kenaikan paling besar pada 2025" : "The largest rise came in 2025"], notes: ms ? "Baca carta dari kiri ke kanan." : "Read the chart left to right.", citations: [`${src}`] },
    { layout: "table", kicker: "PATHWAYS", title: ms ? "Tiga laluan, tiga tempoh" : "Three pathways, three durations", table: { header: [ms ? "Laluan" : "Pathway", ms ? "Tempoh" : "Duration", ms ? "Instrumen" : "Instrument"], rows: [[ms ? "Notifikasi kosmetik" : "Cosmetic notification", ms ? "3 hari bekerja" : "3 working days", "Garis Panduan Kawalan Produk Kosmetik"], [ms ? "Pendaftaran ubat tradisional" : "Traditional medicine registration", `[SAHKAN: ${ms ? "tempoh semasa" : "current duration"}]`, "DRGD"], [ms ? "Sijil Halal" : "Halal certificate", ms ? "30 hari bekerja" : "30 working days", "MPPHM (Domestik) 2020"]], source: `${src}` }, notes: null, citations: [] },
    { layout: "diagram", kicker: "PROCESS", title: ms ? "Laluan notifikasi dalam lima langkah" : "The notification pathway in five steps", diagram: { kind: "flow", steps: [{ label: ms ? "Semak formulasi" : "Screen the formula", detail: ms ? "Annex II, III, IV, VI, VII" : "Annex II, III, IV, VI, VII" }, { label: ms ? "Sedia PIF" : "Build the PIF", detail: ms ? "Penilaian keselamatan ditandatangani" : "Signed safety assessment" }, { label: ms ? "Hantar Quest 3+" : "Submit on Quest 3+", detail: ms ? "Satu produk, satu notifikasi" : "One product, one notification" }, { label: ms ? "Bayar fi" : "Pay the fee", detail: `[SAHKAN: ${ms ? "fi semasa" : "current fee"}]` }, { label: ms ? "Terima nombor" : "Receive the number", detail: ms ? "Sah dua tahun" : "Valid two years" }], events: [], rows: [], cols: [], cells: [] }, notes: null, citations: ["Garis Panduan Kawalan Produk Kosmetik, NPRA"] },
    { layout: "kpi", kicker: "AT A GLANCE", title: ms ? "Angka yang perlu diingat" : "The figures to remember", kpi: [{ label: ms ? "Had asid salisilik (bilas)" : "Salicylic acid cap (rinse-off)", value: "2%", note: "Annex III/98" }, { label: ms ? "Tempoh sah notifikasi" : "Notification validity", value: ms ? "2 tahun" : "2 years", note: "NPRA" }, { label: ms ? "Aduan 2025" : "Complaints 2025", value: "838", note: src }], notes: null, citations: [] },
    { layout: "two-column", kicker: "OBLIGATIONS", title: ms ? "Wajib berbanding disyorkan" : "Mandatory against recommended", leftHeading: ms ? "Wajib" : "Mandatory", rightHeading: ms ? "Disyorkan" : "Recommended", bullets: [ms ? "Notifikasi sebelum pasaran" : "Notify before placing on the market", ms ? "PIF tersedia untuk audit" : "PIF available for audit"], bulletsRight: [ms ? "Ujian kestabilan 12 bulan" : "12-month stability data", ms ? "Ujian cabaran pengawet" : "Preservative challenge test"], notes: null, citations: [] },
    { layout: "quote", title: ms ? "Apa yang dikatakan pengawal selia" : "What the regulator says", quote: { text: ms ? "Notifikasi bukan kelulusan." : "Notification is not approval.", by: "NPRA, Garis Panduan Kawalan Produk Kosmetik" }, notes: null, citations: [] },
    { layout: "image", title: ms ? "Label yang mematuhi" : "A compliant label", image: { prompt: ms ? "Gambar rapat label produk kosmetik di atas meja makmal, tiada teks" : "Close-up of a cosmetic product label on a laboratory bench, no readable text", caption: ms ? "Contoh susun atur label" : "Example label layout", sourceName: null }, bullets: [ms ? "Nama produk dan fungsi" : "Product name and function", ms ? "Senarai ramuan menurun" : "Ingredients in descending order"], notes: null, citations: [] },
    { layout: "cards", kicker: ms ? "LANGKAH SETERUSNYA" : "NEXT STEPS", title: ms ? "Tiga keputusan sebelum kelompok seterusnya" : "Three decisions before the next batch", subtitle: ms ? "Setiap kad satu pemilik dan satu tarikh." : "Each card is one owner and one date.", cards: [{ heading: ms ? "Formulasi semula SKU bilas ke 2%" : "Reformulate rinse-off SKUs to 2%", detail: ms ? "R&D, sebelum kelompok seterusnya." : "R&D, before the next batch.", tag: ms ? "TINGGI" : "HIGH" }, { heading: ms ? "Kemas kini label" : "Update the labels", detail: ms ? "Kawal selia dan pembungkusan." : "Regulatory and packaging.", tag: ms ? "SEDERHANA" : "MEDIUM" }, { heading: ms ? "Sahkan tarikh kuat kuasa" : "Confirm the effective date", detail: `[SAHKAN: ${ms ? "tarikh kuat kuasa di Malaysia" : "Malaysian effective date"}]`, tag: null }], notes: ms ? "Tutup dengan keputusan, bukan ringkasan." : "Close on the decisions, not a recap.", citations: [] },
    { layout: "closing", title: ms ? "Soalan" : "Questions", subtitle: p.audience ? p.audience : null, notes: ms ? "Tiga soalan berkemungkinan: had produk tinggal; tempoh peralihan; kos formulasi semula." : "Three likely questions: the leave-on limit; the transition period; reformulation cost.", citations: [] },
  ];
  return { title, subtitle: null, slides: s.slice(0, Math.max(3, Math.min(p.slides, s.length))) };
}

export function mockRewrite(slide: Record<string, unknown>, instruction: string): Record<string, unknown> {
  return { ...slide, title: `${slide.title}`, notes: `${slide.notes ?? ""}\n[mock rewrite: ${instruction}]`.trim() };
}
